FROM node:20-alpine as build

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN apk add --no-cache python3 make g++ 

RUN yarn

COPY . .

RUN yarn build

#---

FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package.json .
COPY yarn.lock .
COPY ormconfig.js .

RUN apk add --no-cache python3 make g++ 

RUN yarn install --production

COPY --from=build /app/dist ./dist

EXPOSE 5001

ENTRYPOINT [ "yarn", "start:prod" ]